### ISSUE TITLE
Create base vaadin addon structure

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#1]
This includes
* Gradle Wrapper setup
* Gradle multi project with addon and demo
* Demo basics (Servlet and UI Class)

**Comment by hybr1dz** [comment]
Hi, what's the current status of this project? I'm interested in trying ChartJS 2 with Vaadin, so i'm curious if there's any schedule/plans on this.

**Comment by moberwasserlechner** [comment]
Hi, I hope to get a first version til May 2016. Maybe earlier depending on my workload.
