### ISSUE TITLE
Update data after component already initialised

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#11]
http://stackoverflow.com/questions/21137768/passing-a-object-from-server-to-client-with-vaadin
https://vaadin.com/wiki/-/wiki/Main/Integrating%20a%20JavaScript%20library%20as%20an%20extension

**Comment by gokhanoner** [comment]
Hi Michael, if it's ok, I want to contribute on this feature and some others also ?

**Comment by moberwasserlechner** [comment]
Hi Gökhan, 

Your contribution would be very welcome. Please create PRs for that. (see https://github.com/moberwasserlechner/vaadin-chartjs#contribute)

If you need help please let me know.

Cheers,
Michael

**Comment by gokhanoner** [comment]
Michael,

I'm gettin error while importing it:

`Could not get unknown property 'BINTRAY_USER'`

I think it's defined on your side but I dont have this prop. set. ??

**Comment by moberwasserlechner** [comment]
Actual I ran into the same issue myself while setting up travisci for another project. 

I'll have it fixed here later this evening.

**Comment by gokhanoner** [comment]
OK, I temp. fix it with adding those properties to gradle.prop files. But gave another problem.

I made some changes & also update the demo. But I cannot compile demo. Is there something missing/commented on demo to prevent it?

ps: I developed with maven so little experience with gradle, so maybe I couldn't figure it out. sorry for that.

**Comment by moberwasserlechner** [comment]
My setup for developing vaadin plugins right now is:
* Eclipse Neon
* Gradle IDE (http://dist.springsource.com/release/TOOLS/update/e4.6/  -> Core / Eclipse Integration for Gradle -> Gradle IDE)

Import to Eclipse
* Clone the repo
* File ->Import... -> Gradle (STS) -> Gradle (STS) Project -> Select the repo -> Hit the "Build Model" button
* Check all 3 checkboxees and Finish

I create #25 to address your problems and make contribution easier. I think it would be best you postpone your work until I've resolved this issue.

Could you please give me a few insights in your development environment?

**Comment by gokhanoner** [comment]
Hi,
I'm using 

- Eclipse Mars
- [Eclipse Plugin for Gradle](https://projects.eclipse.org/projects/tools.buildship)

Vaadin Gradle plugin seem to work with IDE, but If demo don't use any addons, which is not, you dont need that addon at all. We can use just gradle as a build tool. If It's OK, I can look at that.

Example project setup: https://github.com/spring-guides/gs-crud-with-vaadin

Please let me know so I can go step by step.

Also, do demo need to be a war application, is jar ok ? ( For deploying demo server ) It would be much more simpler this way.

Last thing, is there a specific reason for you to build with Gradle ? I believe maven would be much more easier I believe.

Also, can you move demo to a new repo ? That will also make the setup simple ..

**Comment by gokhanoner** [comment]
UPDATE:

I've succesfully completed this issue. The changes where minimal.

How I did test:

- I've made changes on addon & publish changes to local Maven repo using `publishToMavenLocal` param.
- I've created a new demo project, same source code but using maven (I believe I can use gradle also but it was easier) and instead of referring addon module, I've included the newly published addon, 0.3.0-SNAPSHOT, resolved from local repo.
- Also sprign boot config works as well.

-

**Comment by moberwasserlechner** [comment]
Hi,

great to hear.

Try to integrate your new **view** classes to the demo, so I get the idea (I must not be complete as I could fix any issues after merging) or add the example code as a comment. 

After that please create a **pull request** so I can review the changes and merge it.

Cheers and gn8,
Michael

**Comment by gokhanoner** [comment]
Michael,

I also manage to run demo on Idea, using your current structure with spring-boot. Do you want me to update those changes also ?

**Comment by moberwasserlechner** [comment]
Not directly.

Please move those changes to another branch and create another pull request.

**Comment by gokhanoner** [comment]
OK, I just created a pull request for first part, refreshing data, also added a view as an example.

**Comment by moberwasserlechner** [comment]
Thanks.
