### ISSUE TITLE
Chart image download

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#21]
A user wants to download the current chart by clicking a button (vaadin button).

It looks like I have to call a js function on the connector using `com.vaadin.ui.AbstractJavaScriptComponent.callFunction(String, Object...)` and then call the server with a function registered by `com.vaadin.ui.AbstractJavaScriptComponent.addFunction(String, JavaScriptFunction)`

I havenot found a method, which can retrieve the return value of a javascript function.

Resources:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
https://github.com/chartjs/Chart.js/search?utf8=%E2%9C%93&q=toBase64Image

```
    this.getImageDataUrl= function() {
         // call on function registered by server side component
         self.sendImageDataUrl(chartjs.toBase64Image());
    }
```

**Comment by dyorgio** [comment]
Take care with animations: 

http://stackoverflow.com/questions/20206038/convert-charts-js-canvas-chart-to-image-using-todataurl-results-in-blank-imag

Good approach ask JS component for Image URL, maybe some facilities methods can help, like:
```java
// Create a default button with action listener to download image.
chart.createDownloadButton();
// and/or
// Include action listener to download image in an existent Button
chart.configureDownloadButton(Button b);
```

**Comment by moberwasserlechner** [comment]
I will rewind my current approach (serverside), which does not work properly to meet the above clientside requirements first and to support Java7 for one further release.

**Comment by compengi** [comment]
Just wanted to ask if there is any update on this feature.

**Comment by kegoe** [comment]
#86 adds a dropdown menu with customizable actions and a default action allowing to download the image without sending it to the server

**Comment by moberwasserlechner** [comment]
@kegoe I tried the your demo for downloading and actions added like 
```
        chart.addMenuEntry("Download: Configure Transparent Bg", () -> {
            chart.setDownloadSetWhiteBackground(false);
        });
        chart.addMenuEntry("Download: Configure White Bg", () -> {
            chart.setDownloadSetWhiteBackground(true);
        });
```
are not working.

I moved the features from both your PR to their own views, so users can find them easier.

So this code is acutally located https://github.com/moberwasserlechner/vaadin-chartjs-demo/blob/5b9da7ee6b2373500e68c5fefa0719f6f7e889ee/src/main/java/com/byteowls/vaadin/chartjs/demo/ui/charts/DownloadChartView.java#L78

**Comment by kegoe** [comment]
@moberwasserlechner, I have to admin, that the actions are pretty confusing and I actually had to figure out again, what I did there: the "Download: Configure..." actions simply change the download options but do not start the download (they are actually examples for custom actions). Only the "Download PNG" action actually starts the download and is using the settings set by the other two actions.

**Comment by moberwasserlechner** [comment]
Ah I see ;). You wanted users to be able to add custom menu entries to the drop down.

I'll change the example so its more obvious. Showing a notification or sth esle.
