### ISSUE TITLE
Make contributing to the project easier

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#25]
Right now there these problems:
* BINTRAY properties are required. For future use with TravisCI use the solution in jopencage.
* Gradle Vaadin Plugin pulls in jetty which prevents the spring boot app demo to start.
Currently I commented the gradle-vaadin-plugin section in demo/build.gradle. The commenting might cause the problems in #11 
* Right now developing vaadin addons only works with Eclipse and the Gradle IDE (http://dist.springsource.com/release/TOOLS/update/e4.6/)
* Add step by step setup to contribute section in readme.
* I would like to develop in IDEA myself but was not able to get the Gradle multiproject running

**Comment by moberwasserlechner** [comment]
For IDEA dividing addon and demo into 2 separate repositories might be the best and afaik the only option.

**Comment by gokhanoner** [comment]
Do you need a war for demo, or is jar deployment OK ? I'll change the project structure so spring-boot build for demo work in idea and eclipse also. I also applied the changes for BINTRAY properties, I can submit that one with it or separately.

**Comment by moberwasserlechner** [comment]
Yes I need the war-file do not restructure that.

It's ok for me, if you add the BINTRAY properties in the same PR as the spring boot build for idea and eclipse.

**Comment by moberwasserlechner** [comment]
Addionally I did:
* Drop Gradle Vaadin Plugin because not needed for this addon. A few things have to be done manually now
  * Explicit Vaadin dependencies, which is better because it's more readable
  * Compile demo theme. Task "compileVaadinScss"
  * Write addon metainf attributes needed for uploading in vaadin directory
I hope this doesnot break the setup in IDEA. Eclipse works perfectly.
* Contribution section for eclipse improved. Getting the project up and running should now work like a charm. No Eclipse Gradle plugin is needed.
* Removed widgetset because no client side classes or gwt based addons are used
