### ISSUE TITLE
Download Behavior

### ISSUE THREAD

**Issue by dyorgio** [moberwasserlechner/vaadin-chartjs#36]
Hi, nice add-on!

I observed some stranger behavior on "download as PNG" feature:

http://vaadin-demos.qqjtxeeuih.eu-central-1.elasticbeanstalk.com:5600/#!pie-chart-download

On Chrome I don't need to make nothing (press the download button), only use second mouse button and use "Save image" option.

On Safari (MacOS 10.12.1) I couldn't download, and demo notifications never disappears.

What is the correct behavior for this example?

**Comment by moberwasserlechner** [comment]
Hi,

the download feature is currently under active development in #21 and will be included in release [0.4.0](../milestone/4).

The "Save image" option is *browser specific* and works in Chrome and in Firefox for every html canvas element. I tried the same with Safari and IE 11 but could not see such option. (Tested at http://www.chartjs.org/)

#21 targets a browser independent solution, which I will describe there.

Hope this helps.

BR, Michael

**Comment by dyorgio** [comment]
Nice! tks for response
