### ISSUE TITLE
Chart size problem

### ISSUE THREAD

**Issue by gokhanoner** [moberwasserlechner/vaadin-chartjs#37]
When set the chart size  using setSizeFull(), i expect to see the chart sized correctly, but instead it overflows and some part is not seen on the screen.

**Comment by moberwasserlechner** [comment]
Could you please provide a example because in the demo I don't see that behaviour.

**Comment by dyorgio** [comment]
Same problem here, but with two behaviors:

When navigate to view (Problem):
<img width="870" alt="captura de tela 2017-01-04 as 16 21 44" src="https://cloud.githubusercontent.com/assets/1438251/21653841/44678560-d29a-11e6-9ea3-3a9e8f34f37e.png">

When call browser refresh (Ok):
<img width="884" alt="capura de tela 2017-01-04 as 16 21 59" src="https://cloud.githubusercontent.com/assets/1438251/21653848/5097130a-d29a-11e6-8053-9e1843a9ace3.png">

No mystery on layout, just setSizeFull() on Chart component.

**Comment by moberwasserlechner** [comment]
@dyorgio thanks for the clarification

**Comment by dyorgio** [comment]
@moberwasserlechner @gokhanoner 
If you put on charts-connector.js this line:
```javascript
canvas.setAttribute('height', '100%');
```

The problem stops, but, in my retina display (HDPi), the chart appears smooth (bad rendered).

**Comment by moberwasserlechner** [comment]
@dyorgio 
Your retina display issue might be related to https://github.com/chartjs/Chart.js/issues/3575.

Could you please share your configuration, because in the mentioned issue resizing problems appear if 'responsive' option was set to false.

**Comment by dyorgio** [comment]
@moberwasserlechner I made new test with this modification:

* Update Chartjs to 2.4.0.

Now the problem only occurs if I use 
```java
chart.maintainAspectRatio(true).
```
But, using 
```java
chart.maintainAspectRatio(false)
```
works perfectly to me, including responsive resizing.

Animations stopped to work using % sizes, if I change to pixels animations works ok.

**Comment by Maegar** [comment]
@moberwasserlechner 
I investigate some time for analysing why the chart is not sized correctly
I find the following in chartjs-connector.js:
`if (state.width > 0) {`

The width in state object is a string  (e.g. 100%)  state.width > 0 will always return false. If you change the line to state.width.length > 0  or something similar it should work.

Best regards

**Comment by moberwasserlechner** [comment]
@Maegar thx for that. I hope I can get a new release ready soon.

**Comment by gokhanoner** [comment]
I'm just looking to the demo site, pie with data refresh example. When I refresh the data, chart size incorrectly until you resize the browser.
