### ISSUE TITLE
Support Axis formating/customization

### ISSUE THREAD

**Issue by dyorgio** [moberwasserlechner/vaadin-chartjs#39]
Include on Ticks config the userCallback property:

http://stackoverflow.com/questions/36918887/chart-js-2-0-formatting-y-axis-with-currency-and-thousands-separator

Example:

https://jsfiddle.net/4sLxyfya/7/

**Comment by dyorgio** [comment]
Hi @kegoe, sadly I'm working with a private fork of this repo.
I would like to return to use this codebase as binary dependency only in the future, but I need the support to pass function to chartjs.

**Comment by kegoe** [comment]
#87 solves this while keeping the elemental.json code

**Comment by dyorgio** [comment]
Very nice solution@kegoe, transfer js functions as String and parsing it on js callback code was my initial idea, but for some reason I gave up to do this. I'm sure that this is a very much elegant solution 🤓
