### ISSUE TITLE
Multiple series in one chart

### ISSUE THREAD

**Issue by neopsis** [moberwasserlechner/vaadin-chartjs#41]
How to build a chart with mixed multiple series? Example bar+line chart is here
[https://jsfiddle.net/carnecro/0xzgmkav/](https://jsfiddle.net/carnecro/0xzgmkav/).

**Comment by moberwasserlechner** [comment]
Please have a look at http://vaadin-demos.qqjtxeeuih.eu-central-1.elasticbeanstalk.com:5600/#!bar-line-combo-chart

This should show you how to build a combo chart.

**Comment by moberwasserlechner** [comment]
As I think the provided link should help you figure it out by yourself. I close this question to keep a clean issue list.
