### ISSUE TITLE
Check Vaadin 8 compatibility

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#44]

**Comment by moberwasserlechner** [comment]
I will most propably wait for Vaadin 8.1 because I didn't find the time for it anyway.

**Comment by flexguse** [comment]
At least one can put vaadin-chartjs into a Vaadin 8 application and a chart is shown. A total incompatibility is not given ;)

**Comment by moberwasserlechner** [comment]
As Vaadin added a new tree in 8.1.0.beta1 I must not rewrite the demo navigation.

**Comment by moberwasserlechner** [comment]
Doing the upgrade I removed the Gradle multiproject and move the demo in its own git repo. https://github.com/moberwasserlechner/vaadin-chartjs-demo

**Comment by moberwasserlechner** [comment]
As @flexguse mentioned I didn't had to change anything after upgrading to vaadin 8.
