### ISSUE TITLE
Question about ChartUtils

### ISSUE THREAD

**Issue by eliasmav** [moberwasserlechner/vaadin-chartjs#46]
Hello, First of all a BIG thank you for the add-on. It is Great.

I have one question, where I can find the "ChartUtils", where are included. I can import all the libraries 
except this one.

Thanks again 
Elias

**Comment by moberwasserlechner** [comment]
Hi Elias,

This class only exists in the demo.

See https://github.com/moberwasserlechner/vaadin-chartjs/blob/master/demo/src/main/java/com/byteowls/vaadin/chartjs/demo/ui/ChartUtils.java#L29

I will rename it into DemoUtils to make its purpose and location clearer.

BR,
Michael

**Comment by eliasmav** [comment]
Perfect,Thank you so much.
You are a REAL professional.
RgdsElias
  

    On Thursday, March 2, 2017 3:11 PM, Michael Oberwasserlechner <notifications@github.com> wrote:
 

 Hi Elias,This class only exists in the demo.See https://github.com/moberwasserlechner/vaadin-chartjs/blob/master/demo/src/main/java/com/byteowls/vaadin/chartjs/demo/ui/ChartUtils.java#L29I will rename it into DemoUtils to make its purpose and location clearer.BR,
Michael—
