### ISSUE TITLE
Different labels on the X-axis (scaleLabel) and in the tooltip (tooltipLabel)

### ISSUE THREAD

**Issue by Fitzchev** [moberwasserlechner/vaadin-chartjs#48]
Hi,

Is there currently a way to do this kind of customization, directly or using an override? I need to display dates without hours in the scale but the full label in the tooltip.

See the jsfiddle below, someone did something similar in javascript, but I don't think that your wrapper implements tooltipTemplate yet.

[https://jsfiddle.net/7z1s1feg/](url)

Thanks in advance.

**Comment by kegoe** [comment]
Note, that the above syntax refers to Chart.js 1.x API

**Comment by kegoe** [comment]
#87 solves this using the callbacks provided by the Charts.js 2.x API
