### ISSUE TITLE
Stretched chart after refreshData()

### ISSUE THREAD

**Issue by hubertooo** [moberwasserlechner/vaadin-chartjs#50]
When I trigger refreshData() chart is is stretched.
Browser refresh, browser resize ... all is perfect.

What am I dooing wrong?

Vaadin 7.7.9
vaadin-chartjs 0.4.0

A bit of source code

```
   private void buildChart() {
           
      configChart = new LineChartConfig();
      
      configChart.data()
              .addDataset(new LineDataset().label("qwerty").backgroundColor("rgba(151,187,145,0.5)"))
              .and()
              .options()
              .responsive(true)
              .title()
              .display(true)
              .and()
              .tooltips()
              .and()
              .scales()
              .add(Axis.X, new DefaultScale()
                      .stacked(true))
              .add(Axis.Y, new DefaultScale()
                      .stacked(true))
              .and()
              .done();

      
      
      Dataset<?, ?> ds = configChart.data().getDatasetAtIndex(0);
      chartLineDataSet = (LineDataset) ds;
      
      
      chart = new ChartJs(configChart);
      chart.setJsLoggingEnabled(true);
      chart.setSizeFull();
   }

   private void chartDataRefresh(Long offset) {
      dataSNR = crDrI122Repo.getAllSnrs();
      
      dataTaskDateString = Util.dateArrayToStringarray(crDrI122Repo.getAllTaskDates());
      configChart.data().labels(dataTaskDateString);

      chartLineDataSet.dataAsList(Util.floatListToDoubleList(dataSNR));
      
      chart.configure(configChart);
      chart.refreshData();
      
   }
```

OK
![huberto_awtfm_agfapoland_2017-06-10_18-32-19](https://user-images.githubusercontent.com/29337096/27004574-520f11f0-4e0b-11e7-9e26-98d284258bdc.jpg)

after reload
![huberto_awtfm_agfapoland_2017-06-10_18-33-12](https://user-images.githubusercontent.com/29337096/27004576-54b2d11c-4e0b-11e7-9578-71737e5dada6.jpg)

ps. vaadin chart js = great job

**Comment by moberwasserlechner** [comment]
This is a bug, unfortunatly you can't do sth against it.

**Comment by moberwasserlechner** [comment]
Upgrade to Chart.js 2.6 does not fix the problem. I guess after refresh I have to trigger a repaint or sth similar. 

In the demo moving on of the splitters also triggers the repaint and the chart is displayed correctly.

**Comment by moberwasserlechner** [comment]
The problem is that after the refresh the width attribute of the canvas is set to 100%.

**Comment by moberwasserlechner** [comment]
Dublicates #23

**Comment by hubertooo** [comment]
sorry for delay ... vacation :)

thx for fast respons 
will you put 1.0.0 to http://jcenter.bintray.com/com/byteowls/vaadin-chartjs/ repository?
only 0.4.0 is awaliable

**Comment by moberwasserlechner** [comment]
As soon as the release is ready I will ;)
