### ISSUE TITLE
Fill options in LineDataset - String

### ISSUE THREAD

**Issue by hubertooo** [moberwasserlechner/vaadin-chartjs#57]
Is it possible to change fill parameter to string?
LineDataset.java

    public LineDataset fill(boolean fill) {
        this.fill = fill;
        return this;
    }

This functionality is good to implement :
http://www.chartjs.org/samples/latest/charts/area/line-datasets.html

![image](https://user-images.githubusercontent.com/29337096/27371812-80d25d62-5662-11e7-955a-279b5a25bb26.jpg)

**Comment by moberwasserlechner** [comment]
This was done with #51, but it doesnot with string but with enums and another method. See the demo for code samples http://vaadin-demos.qqjtxeeuih.eu-central-1.elasticbeanstalk.com:5600/#!line-fill-chart
