### ISSUE TITLE
Add support for annotation plug-in

### ISSUE THREAD

**Issue by micw** [moberwasserlechner/vaadin-chartjs#63]
Hello,
I'm trying to draw some threshold lines in my chart. For horizontal lines, I use an extra data set with constant value - works but it's not optimal. After reading a bit, I found the following plug-in that allows to add some annotations (boxes, lines) to charts: https://github.com/chartjs/chartjs-plugin-annotation
If you could add support for it, this would be great!
Kind regards,
Michael.

**Comment by moberwasserlechner** [comment]
I will extend the PR with some addional features the annotation plugin offers.

* Vertical lines
* Box annotation

**Comment by moberwasserlechner** [comment]
> Annotations work with line, bar, scatter and bubble charts that use linear, logarithmic, time, or category scales. Annotations will not work on any chart that does not have exactly two axes, including pie, radar, and polar area charts.

Annotations only work with charts having exactly two axes like line, bar, scatter and bubble charts.

**Comment by moberwasserlechner** [comment]
The integration now supports everything the plugin does except click events.
