### ISSUE TITLE
Scroll not working

### ISSUE THREAD

**Issue by Styshak** [moberwasserlechner/vaadin-chartjs#69]
Scroll not working when mouse cursor hover chart
```
var myChart = new Chart(ctx, {...});
myChart.ctx.canvas.removeEventListener('wheel', myChart._wheelHandler);
```
This will fix, but how can make from vaadin?

https://stackoverflow.com/questions/44487554/how-to-disable-canvas-elements-from-hijacking-mouse-wheel-when-scrolling-through

**Comment by moberwasserlechner** [comment]
As the stackoverflow answer states this is caused by the zoom/pan plugin, which is always active and captures the wheel event. I need to release the event if the plugin is not used/configured

**Comment by moberwasserlechner** [comment]
The answer is a little outdated because in the current version of the zoom plugin the handler is located 
```
myChart.zoom_wheelHandler
```
