### ISSUE TITLE
Chart is not destroyed

### ISSUE THREAD

**Issue by Styshak** [moberwasserlechner/vaadin-chartjs#70]
When you build chart and close vaadin view\window etc, chart instanses is not destroyed. Stored in memory until you restart your browser. For check count of charts  - Chart.instances in browse console. Is it bug?

**Comment by moberwasserlechner** [comment]
I'm not really sure if this is really a issue. 

I added a public destroy() method on the chart's entry point but I will not call it on detach() because in my demo application I would have to init the chart every time I enter a view.
