### ISSUE TITLE
Android - gradle build issue

### ISSUE THREAD

**Issue by achinverma** [moberwasserlechner/vaadin-chartjs#72]
Hi ,

I am using your library in my app when i added this library in my gradle i am getting some issue , please look at the below error , please guide me .

**Error:java.lang.ClassNotFoundException: Class javax.servlet.http.HttpSessionBindingListener not found
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.**
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/18.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/43.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/44.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/37.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/38.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/23.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/8.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/4.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/35.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/26.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/27.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/39.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/40.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/20.jar --input /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/41.jar --output /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/desugar/debug/42.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/classes/debug --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/23.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/24.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/25.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/26.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/28.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/29.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/30.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/31.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/32.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/33.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/35.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/36.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/37.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/38.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/39.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/40.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/41.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/42.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/43.jar --classpath_entry /home/dev/Documents/talup/talupp-android/app/build/intermediates/transforms/stackFramesFixer/debug/44.jar --bootclasspath_entry /home/dev/android-sdk-linux/platforms/android-26/android.jar --bootclasspath_entry /home/dev/android-sdk-linux/platforms/android-26/optional/org.apache.http.legacy.jar --bootclasspath_entry /home/dev/Documents/android-studio-3/jre/jre/lib/resources.jar --bootclasspath_entry /home/dev/Documents/android-studio-3/jre/jre/lib/rt.jar --bootclasspath_entry /home/dev/Documents/android-studio-3/jre/jre/lib/jsse.jar --bootclasspath_entry /home/dev/Documents/android-studio-3/jre/jre/lib/jce.jar --bootclasspath_entry /home/dev/Documents/android-studio-3/jre/jre/lib/charsets.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

**Comment by achinverma** [comment]
My build.gradle file and i am using java 8

```
//noinspection GradleCompatible
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "app.com.talupp"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '26.0.2'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.squareup.retrofit2:retrofit:2.1.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'com.github.bumptech.glide:glide:3.8.0'
    //compile 'com.github.bumptech.glide:glide:4.5.0'
    //annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0'
    compile 'com.byteowls:vaadin-chartjs:1.1.1'
    compile 'com.romandanylyk:pageindicatorview:0.2.0@aar'
    implementation 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.amazonaws:aws-android-sdk-core:+'
    compile 'com.amazonaws:aws-android-sdk-s3:+'
    compile 'com.amazonaws:aws-android-sdk-ddb:+'
    compile 'com.github.lzyzsd:circleprogress:1.2.1'
    compile 'com.android.support:multidex:1.0.2'
    compile 'com.github.ed-george:AndroidVimeoExtractor:1.1.1'
}
```

**Comment by moberwasserlechner** [comment]
This lib is a Vaadin addon you need Vaadin! You cant use it in a Android app and its not intended to be.

**Comment by achinverma** [comment]
@moberwasserlechner , ok , so please tell me how can i use Vaadin in my android project , i want to use this chart.

**Comment by Maegar** [comment]
You can't. By the way RTFM. Use google and search a Chart Library for your App.

**Comment by achinverma** [comment]
ok , it looks useless Library :-1:
