### ISSUE TITLE
Chart Y range set to wrap aggressively

### ISSUE THREAD

**Issue by moovida** [moberwasserlechner/vaadin-chartjs#84]
### Your issue description

If I load three datasets with only one value in a barchart, the Y Axis is wrapped in a way that the minimum of the datasets disappears. It might be better to set some buffer around it. 

Is there a way to set the Y Axis range from the API, I couldn't find one?

Not sure if I explained myself, the screenshot below is more clear.

### Your configuration

Vaadin 8

### Your screenshots

As you can see in the screenshot, the value 6 is not visible (the red dataset called "Notes").

![vaadin_chartjs](https://user-images.githubusercontent.com/390250/43636333-1485be0a-9712-11e8-9366-7d2fbba97be1.png)

And thanks for this fantastic piece of add-on!

PS: small update comment. 
I now see that it is as simple as: 
```
LinearScale linearScale = new LinearScale();
linearScale.ticks().beginAtZero(true);
```
It might anyways be an idea to use a bit of buffer around the min/max values. Feel free to render this issue invalid, since in fact the API to solve this is there. Sorry for the noise.

**Comment by moberwasserlechner** [comment]
I think Chart.Js has the same behaviour, because I'm doing nothing other than pass the config to Chart.Js.

Did you eventually try to build your use case in Javascript? Are the results the same or are they different?

**Comment by moovida** [comment]
Hi, I am afraid I am not much a javascript guy so I didn't try it.

**Comment by moberwasserlechner** [comment]
Np. I close the issue for now.
