### ISSUE TITLE
Vaadin 12 Support

### ISSUE THREAD

**Issue by ugurdoksan** [moberwasserlechner/vaadin-chartjs#90]
I am using Vaadin 12 and Vaadin 13 is on the way... When will the Vaadin 10+ support be released?

**Comment by moberwasserlechner** [comment]
There is no plan to upgrade to Vaadin 10+ in the next month.

Note: This is a open source project I do in my spare time. I have no sponsor or other donations. So maybe you should think about how demanding a feature request or a comment should be.

**Comment by moberwasserlechner** [comment]
Dublicates #62
